name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # This step ensures that Redis is up and running
    - name: Check Redis
      run: |
        sudo apt-get update
        sudo apt-get install -y redis-tools
        redis-cli -h 127.0.0.1 ping

    # Build the hospital_service project
    - name: Build hospital_service with Maven
      run: mvn -B package --file hospital_service/pom.xml

    # Build the patient_service project
    - name: Build patient_service with Maven
      run: mvn -B package --file patient_service/pom.xml

    # Build the emergency_responder project
    - name: Build emergency_responder_service with Maven
      run: mvn -B package --file emergency_responder_service/pom.xml

    # Build the api_gateway project
    - name: Build api_gateway with Maven
      run: mvn -B package --file api_gateway/pom.xml
